### ISSUE TITLE
Build Team Website

### ISSUE THREAD

**Issue by apoliveira** [apoliveira/software-engineering#1]
Include all of the specs asked for by Val

**Comment by apoliveira** [comment]
I've just finished putting the final(?) updates on the website. Let me know what you guys want as your bios

http://snoopy.rlc.manhattan.edu/~aoliveira01.student/soft_eng

**Comment by tmwhite** [comment]
Tyler White
- Renaissance Man of the Year Award Winner[1995]
- Dog Lover
- Using a decision tree to lead me
- And currently reading "Physically Based Rendering" by Rharr Humphrys so I
  can make a world that's better than mine

**Comment by apoliveira** [comment]
updated

**Comment by nymim93** [comment]
import random

def quickSort(A):
        if len(A) <= 1:
                return A
        else:
                return quickSort([x for x in A[1:] if x < A[0]]) + [A[0]] +
quickSort([x for x in A[1:] if x >= A[0]])

test1 = [random.randint(1, 100) for i in range(11)]
test = test1[::-1]
print test
print quickSort(test)

def mergeSort(A):
        if(len(A) == 1):
                return A
        else:
                mid = len(A)/2
                B = mergeSort(A[:mid])
                C = mergeSort(A[mid:])
                return merge(B, C)

def merge(A, B):
        C = []
        while len(A) != 0 and len(B) != 0:
                if(A[0] > B[0]):
                        C += [B.pop(0)]
                else:
                        C += [A.pop(0)]

        return C + A + B

print mergeSort(test)

def heapsort( A ):
        B = A[:]
        # build heap
        for i in range(1, len(B)+1):
                maxHeapify(B, len(B) - i)

        # get the sorted array
        C = []
        while len(B) != 0:
                # swap the top with the last
                swap( B, 0, len(B) - 1 )
                # add to the end of C
                C += [B.pop(len(B) - 1)]

                # max heapify the top element
                maxHeapify(B, 0)
        return C

def maxHeapify( A, index ):
        lastIndex = len(A) - 1
        leftIndex = (index * 2) + 1
        rightIndex = (index + 1) * 2

        # if it doesn't have a left node
        if leftIndex > lastIndex:
                return
        # if the node doesn't have a right node
        elif rightIndex > lastIndex:
                # swap the node with it's left child if it is less than
                if(A[leftIndex] < A[index]):
                        swap(A, index, leftIndex)
        # if it has both left and right nodes
        else:
                #check to see if the left node is greater
                if(A[leftIndex] < A[rightIndex]):
                        if(A[leftIndex] < A[index]):
                                swap(A, index, leftIndex)
                                maxHeapify(A, leftIndex)
                else:
                        if(A[rightIndex] < A[index]):
                                swap(A, index, rightIndex)
                                maxHeapify(A, rightIndex)

def swap( A, x, y ):
        tmp = A[x]
        A[x] = A[y]
        A[y] = tmp

print heapsort(test)

**Comment by nymim93** [comment]
Mim Cobaj
- Likes to wear viking hats
- Cannot stop eating Buffalo Wild Wings
- Solved an NP-complete problem in polynomial time
- Owns a dog with a loud squeak for a bark

**Comment by apoliveira** [comment]
Team Website is all set. We might make it dynamic (have a small admin backend), but it isn't necessary.
