### ISSUE TITLE
Using Github issues as a history

### ISSUE THREAD

**Issue by apoliveira** [apoliveira/software-engineering#2]
Tyler and I think we should have 5 types of issue labels:

Discussion: like this, if we want to open up an idea for debate
Feature: the main requirements/details for a feature
Bug: raising attention to a bug and its discussion
Question: add this to any issue you have a question about
Help Wanted: if any task becomes overwhelming add this to show the team

Labels can be added/deleted at any time. Any other thoughts?

**Comment by nymim93** [comment]
So we should keep this as professional as possible? Sounds good to me ;D lol #pro

**Comment by apoliveira** [comment]
Since this is agreed upon. I'm closing the ticket. Should any of us want to bring it up for discussion again simply reopen the ticket.
